---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mattsday/le-pcf-on-gcp-base
    tag: "latest"

inputs:
- name: git-pipeline

params:
  GCP_CREDENTIALS:
  GCP_HTTPS_PROXY: 
  CERT_RENEW_BEFORE:

run:
  path: git-pipeline/scripts/check-cert.sh