---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mattsday/le-pcf-on-gcp-base
    tag: "latest"

inputs:
- name: git-pipeline

outputs:
- name: app-info

run:
  path: git-pipeline/scripts/update-cert.sh

params:
  GCP_CREDENTIALS:
  GCP_HTTPS_PROXY:
  CF_DOMAINS:
  LE_SERVER:
  LE_EMAIL:
  PCF_USER:
  PCF_OPSMGR: 
  PCF_PASSWD: 
  GCP_CERT_NAME: 
  GCP_HTTPS_PROXY: 
  OPSMAN_CERT_NAME: 
  GCP_DNS_WAIT: 
  SKIP_PAS_CERT: 
  SKIP_PKS_CERT: 
  SKIP_HARBOR_CERT:
  SKIP_OPSMAN_APPLY:
  SKIP_GCP_CERT: